# This file was generated by GoReleaser. DO NOT EDIT.
cask "genv" do
  version "4.3.0"

  on_macos do
    on_arm do
      sha256 "70789bb59a6472a8cf782c1f1a3db7900fffd336b3ad997fdca8f41df8198e8c"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b6a5b0491d841130499b614ca0719d251aad67f87c27bf78e4c33b6de0d31611"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b46375a8a0195bbe1864adb081a7e555ff1b31451b43890b66b76b5a9f95568e"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c3f8a279819bd0451b81cb23617dcb3525e14d0cd1415a70d03b67b3a1dc571"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_linux_amd64.tar.gz"
    end
  end

  name "genv"
  desc "Track, sync, and reproduce your software environment across Linux, macOS, Windows, and WSL2."
  homepage "https://github.com/ks1686/genv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "genv"

  postflight do
    if OS.mac?
      plist = File.expand_path("~/Library/LaunchAgents/genv.updates.plist")
      if File.exist?(plist)
        system_command "#{staged_path}/genv", args: ["updates", "start"]
      end
    end
  end

  # No zap stanza required
end
