# This file was generated by GoReleaser. DO NOT EDIT.
cask "genv" do
  version "2.2.0"

  on_macos do
    on_intel do
      sha256 "9dfeb1948d7f887aadfa8205a6002dbc1c5099a743a6200509272dfa4ded143f"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ee79ec52f1f76a85e9b91d13ee68530cf65df445c66406030a3eb6451740e1f"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "14e71d103928232419a2fc9d2b40c589bb44c8d2cbff9abcbc6602ca6e741e0c"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ea4acf9fc6655fc9a479a796a519b57c2e5cbc34d35c43a90b42d58553cb6ce"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "genv"
  desc "Track, sync, and reproduce your software environment across Linux, macOS, and WSL2."
  homepage "https://github.com/ks1686/genv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "genv"

  # No zap stanza required

end
