# This file was generated by GoReleaser. DO NOT EDIT.
cask "genv" do
  version "4.0.4"

  on_macos do
    on_intel do
      sha256 "7045736201f3077de076b164c605516fa1de4bfec40597fb64a35cb913e812fb"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b562ef5ef4330335bee794f427a395bab26fe5da136fa29fdc1602343b1ad52"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd052936d4c0e6029cac2a9cca9cfca2ce9a4dba74cc9d0c37219e9c722b9f5d"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b5b870ce9a411e878b552a0c81e8efea669899cbc4f6ed84f8405b4b98bf9122"
      url "https://github.com/ks1686/genv/releases/download/v#{version}/genv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "genv"
  desc "Track, sync, and reproduce your software environment across Linux, macOS, Windows, and WSL2."
  homepage "https://github.com/ks1686/genv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "genv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/genv"]
      # launchd caches the adhoc codesign identity; reload the updates
      # agent after binary replace so scheduled runs keep working.
      plist = File.expand_path("~/Library/LaunchAgents/genv.updates.plist")
      if File.exist?(plist)
        system_command "#{staged_path}/genv", args: ["updates", "start"]
      end
    end
  end

  # No zap stanza required

end
