# This file was generated by GoReleaser. DO NOT EDIT.
cask "gpm" do
  name "gpm"
  desc "Track, sync, and reproduce your software environment across Linux, macOS, and WSL2."
  homepage "https://github.com/ks1686/gpm"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gpm"

  on_macos do
    on_intel do
      url "https://github.com/ks1686/gpm/releases/download/v#{version}/gpm_#{version}_darwin_amd64.tar.gz"
      sha256 "9bcb009b88542748b42afa3432d2034904c3b9da86c0768d5758de4abf62b6f8"
    end
    on_arm do
      url "https://github.com/ks1686/gpm/releases/download/v#{version}/gpm_#{version}_darwin_arm64.tar.gz"
      sha256 "39ad7c4df1ba72953633ecf4b34c7bcb216c6f6684bad60fc745744e57a74735"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ks1686/gpm/releases/download/v#{version}/gpm_#{version}_linux_amd64.tar.gz"
      sha256 "a33d14477b42a87c6c4794a15a595c742adb5d985afaf5179ca7f27c9523e272"
    end
    on_arm do
      url "https://github.com/ks1686/gpm/releases/download/v#{version}/gpm_#{version}_linux_arm64.tar.gz"
      sha256 "1c086b3dfd75fa1022f5e3597ea11d46abeed6d16e9c041b8ee4291a065b555b"
    end
  end

  # No zap stanza required
end
