# This file was generated by GoReleaser. DO NOT EDIT.
cask "peaproxy" do
  version "1.6.4"

  on_macos do
    on_arm do
      sha256 "78d4d00de2079382ed1d1360383cbfe8729134d0a0e269de18bd8c3f3f07c599"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "701c12ecb1cf9370edae19b3709b865b04444a7e153091f93fea2e81bb14ff13"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ca6a9ea570edb963e2ef113cc094ce1de1293dccc1897c776314eeb263608d16"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b3b2d6c11f34237412e93ec573cc50f0d0e51ce1897cfe3750109f9f24f13af6"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "peaproxy"
  desc "Localhost multi-provider AI gateway with API keys, local runtimes, and optional subscription OAuth."
  homepage "https://github.com/ks1686/peaproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peaproxy"

  # No zap stanza required
end
