# This file was generated by GoReleaser. DO NOT EDIT.
cask "peaproxy" do
  version "3.0.3"

  on_macos do
    on_arm do
      sha256 "753cbd0ddde84672fcfc098076cb0176c462b1cf5a1d5ea3b50b831e890395c5"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "46a5572da4bac82cd6e7242759bfff6f4bfbbc1654337fef7f837f9e3d4ac2f6"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "167b426dfbbbb91772c18d36b0fb3c1cc18e240ebdccfbf286399eac59d0828b"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6809d455bc2fed3c95802a1c08c59f96019b774a0415bb205352c2f6a1b9bc0b"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "peaproxy"
  desc "Localhost multi-provider AI gateway with API keys, local runtimes, and optional subscription OAuth."
  homepage "https://github.com/ks1686/peaproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peaproxy"

  # No zap stanza required
end
