# This file was generated by GoReleaser. DO NOT EDIT.
cask "peaproxy" do
  version "2.0.2"

  on_macos do
    on_arm do
      sha256 "7422e9febbfbc33187c780c4d3a2286d78aa063b41384bcba8cf7b85ef4187e0"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4f4a580d4908eb28ddd7585a5732ad34e5d7f32dd6525b0140d6f09c33c61e46"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5f73f03492d0c598bc8b2443b256f0dca212b05bd4c064309815d84de21ca872"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9da517889af512757937b2ef2db13db10038553b11feed49d2d76a473cb7f9f9"
      url "https://github.com/ks1686/peaproxy/releases/download/v#{version}/peaproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "peaproxy"
  desc "Localhost multi-provider AI gateway with API keys, local runtimes, and optional subscription OAuth."
  homepage "https://github.com/ks1686/peaproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peaproxy"

  # No zap stanza required
end
